name: "Bluetooth Radar Pro"
description: "Radar Pro: State Reflection Engine (Bermuda Optimized)"
version: "1.8.0"
slug: "bt_radar_pro"
arch:
  - aarch64
  - amd64
  - armv7
init: false
panel_icon: "mdi:radar"
panel_title: "BT Radar Pro"
ingress: true
hassio_api: true
homeassistant_api: true
host_network: true
options: {}
schema: {}